Feature/milestone1.2
forbole/official-website pull request #184
Opened 2021-01-19 13:24 UTC by rachelhox

## Description

closes #162 

## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-01-26 08:33 UTC, kwunyeung requested changes

2021-01-26 08:33 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/hooks.tsx
> +      getVSYS();
Actually there are only two types of networks you have implemented, `VSYS` and `Cosmos-based`. I think you can reduce footprint and make it more maintainable by rewriting a single `getCosomos` for all `Cosmos-based` chains and a `getVSYS`. You can prepare an array for the settings of different `Cosmos-based` chains and pass corresponding values to the function. The initial object in the `useState` are all the same. You can just create an object with correct values but not repeating everything so many times. And I also find it funny when all keys in the state hooks are `atom`.

2021-01-26 08:33 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/index.tsx
> +  ];
Better make the network names and the icons in single structure of selectedData. For example, you can do
```
const selectedData = [
  {network: cosmos, icon: "cosmos-hub"},
  {network: iris, icon: "iris"},
  ....
]
```
Then you already have an indexed array and you can reference to the correct icon to the corresponding networks.

2021-01-26 08:33 UTC, kwunyeung commented on src/utils/network_info.ts
> +    },
Do you think this structure can be expanded to support the delegation calculations?

2021-01-29 03:34 UTC, kwunyeung requested changes

2021-01-29 03:34 UTC, kwunyeung commented on src/models/network.ts
> +  public totalAtom: string;
I still prefer you change the variable names to a generic one.
```suggestion
  public totalTokens: string;
```

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/components/chart/index.tsx
> +  { title: "cosmosHub", value: 20, color: "#FF6767" },
Please don't hard code the value of the chart.

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/hooks.tsx
> +import { Network } from "@models";
Looks like you have never used this interface?

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/hooks.tsx
> +  const [cosmosNetwork, setCosmosNetwork] = useState([
I think you can just initialize with an empty array with the type. Even if you really would like to put these values in the state, you can also create the entire state in a loop instead of copy and paste and just update 0,1,2,3,4,5,6.....

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/hooks.tsx
> +    await delay(2000);
Any reason to have a 2 second delay for each other call while the `getCosmosBasledNetwork()` is calling 8 networks at the same time?

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/index.tsx
> +  console.log(`index:>>>>>>>>>>>>>>>`, hookProps);
Remove frontend console.log()

2021-01-29 03:34 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/index.tsx
>        <p>{t("tokensStakedWithForbole")}</p>
You already have all the data in `hookProps`, you can easily calculate the USD value in https://github.com/forbole/official-website/blob/1fbd7a5844896f409896f7fef7faee338bb52db0/src/screens/stake_now/components/forbole_stakes/index.tsx#L41 and the value in the chat in https://github.com/forbole/official-website/blob/1fbd7a5844896f409896f7fef7faee338bb52db0/src/screens/stake_now/components/forbole_stakes/components/chart/index.tsx#L6

Just pass the values into those components.

2021-01-29 07:47 UTC, rachelhox commented on src/screens/stake_now/components/forbole_stakes/index.tsx
>        <p>{t("tokensStakedWithForbole")}</p>
yea! Sorry I wasn't done with this feature `totalUSD` yet when I pushed this specific commit to remote!

2021-01-29 07:48 UTC, rachelhox reviewed
@kwunyeung Please review
Now the donut chart looks sthm like this after calculating the percentage of different networks!
![image](https://user-images.githubusercontent.com/53459742/106246635-60236880-6249-11eb-875e-c679b3e2a762.png)

2021-01-29 09:39 UTC, rachelhox reviewed
@kwunyeung please review!
The donut chart now looks like this:
![image](https://user-images.githubusercontent.com/53459742/106258493-d8ddf100-6258-11eb-837a-4122ed1d634f.png)

2021-01-29 10:07 UTC, kwunyeung submitted a review, later dismissed
LGTM

2021-01-29 10:46 UTC, kwunyeung approved these changes

2021-01-29 10:47 UTC, merged