Milestone 1.2.1
forbole/official-website pull request #193
Opened 2021-02-01 06:15 UTC by rachelhox

## Description

closes #186 

## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-02-04 10:55 UTC, kwunyeung requested changes

2021-02-04 10:55 UTC, kwunyeung commented on src/components/tags/index.tsx
> +            <a href={`/tag/${x.slug}`}>{x.name}</a>
Why use `<a>` directly but not the `<Link>` from `next`? It will not be using the router in `next`.

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/author/index.tsx
> +              <a href={`/blog/${x.slug}`} key={i}>
Same question as above.

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/blog/components/blog_posts/components/post/index.tsx
> +      <a href={`/blog/${slug}`}>
Same here.

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/blog/components/title_posts/index.tsx
> +        <a href={`/blog/${x.slug}`} key={i}>
Hm...?

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/hooks.tsx
> +  console.log(isLoading);
Remove this on frontend.

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/blog_details/components/author/index.tsx
> +        <a href={`/author/${author.slug}`}>
Er...?

2021-02-04 10:55 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/index.tsx
> +        <ClipLoader color="rgba(255, 255, 255)" size={50} />
If you are only using the `ClipLoader`, why not use the loader directly from `Semantic UI`?

https://react.semantic-ui.com/elements/loader/

2021-02-04 11:01 UTC, kwunyeung commented on src/screens/stake_now/components/forbole_stakes/index.tsx
> +        <ClipLoader color="rgba(255, 255, 255)" size={50} />
Even more variations https://fomantic-ui.com/elements/loader.html

2021-02-05 04:36 UTC, rachelhox commented on src/components/tags/index.tsx
> +            <a href={`/tag/${x.slug}`}>{x.name}</a>
I switched it to `<a>` instead of it being inside of `<Link>` in order to get rid of the 404 warning that staging site throws out when visiting tag and author page! Anyways I'm now looking into ways of next.js not routing users to `/tag/[tag].js` with the use of `next/link`

2021-02-08 08:36 UTC, kwunyeung approved these changes
LGTM

2021-02-08 08:37 UTC, merged