Products Page
forbole/official-website pull request #236
Opened 2021-03-09 12:37 UTC by rachelhox

## Description

closes #235 

## Checklist
- [ ] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.

2021-03-15 10:27 UTC, kwunyeung commented
@rachelhox Is it R4R?

2021-03-15 11:02 UTC, rachelhox commented
> @rachelhox Is it R4R?

Not yet! realised the desktop view is a bit off.. working on it rn

2021-03-18 10:57 UTC, kwunyeung requested changes

2021-03-18 10:57 UTC, kwunyeung commented on src/screens/products/components/desmos/index.tsx
> +        <div className="content">
`<li>` should be child of `<ul>` and so this should be a `<ul>` but not a `<div>`.
```suggestion
        <ul className="content">
```

2021-03-18 10:57 UTC, kwunyeung commented on src/screens/products/components/desmos/index.tsx
> +          <a href="https://www.desmos.network/">
If this is one of the list items, the `<a>` should be a child of `<li>`.
```suggestion
          <li><a href="https://www.desmos.network/">
```

2021-03-18 10:57 UTC, kwunyeung commented on src/screens/products/components/big_dipper/components/big_dipper_content/index.tsx
>          <div className="content">
Please read the comment below.

2021-03-18 15:48 UTC, rachelhox commented on src/screens/products/components/desmos/index.tsx
> +          <a href="https://www.desmos.network/">
@kwunyeung this is the `EXPLORER -->` under the list items
![image](https://user-images.githubusercontent.com/53459742/111655168-62b33f00-8844-11eb-932f-b2b23d4454c2.png)

2021-03-18 16:01 UTC, kwunyeung commented on src/screens/products/components/desmos/index.tsx
> +          <a href="https://www.desmos.network/">
Then the `<a>` should be a sibling of the `<ul>`.

2021-03-19 05:08 UTC, kwunyeung requested changes

2021-03-19 05:08 UTC, kwunyeung commented on src/screens/products/components/big_dipper/components/big_dipper_content/index.tsx
>            <a href="https://cosmos.bigdipper.live/">
Same for this `<a>`.

2021-03-20 07:04 UTC, kwunyeung approved these changes

2021-03-20 07:04 UTC, merged